import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

objs = Glob('*.c')
group = DefineGroup('solution_application', objs, depend = ['USING_XIAOZHI_IOT'], CPPPATH = [cwd])
#include all subfolder
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
