import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

objs = Glob('*.c')
group = DefineGroup('solution_application', objs, depend = ['USING_XIAOZHI_IOT'], CPPPATH = [cwd])

Return('group')
