
name: deploy-docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: 安装依赖
        run: |
          cd docs
          corepack enable
          pnpm install --frozen-lockfile

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          cd docs
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: Install COSCMD
        run: |
          pip install coscmd

      - name: Configure COSCMD
        run: |
          coscmd config -a ${{ secrets.COS_DOCS_SECRET_ID }} -s ${{ secrets.COS_DOCS_SECRET_KEY }} -b ${{ secrets.COS_DOCS_BUCKET }} -r ${{ secrets.COS_DOCS_REGION }}

      - name: Upload to COS
        run: |
          coscmd upload -rs --delete --yes ./docs/src/.vuepress/dist/ /projects/xiaozhi/
          echo "Uploaded documentation for docs to COS successfully."
      
      - name: Install TCCLI
        run: |
          pip install tccli
      
      - name: Purge CDN Cache
        run: |
          export TENCENTCLOUD_SECRET_ID=${{ secrets.COS_DOCS_SECRET_ID }}
          export TENCENTCLOUD_SECRET_KEY=${{ secrets.COS_DOCS_SECRET_KEY }}
          export TENCENTCLOUD_REGION=${{ secrets.COS_DOCS_REGION }}
          tccli cdn PurgePathCache --cli-unfold-argument --Paths 'https://docs.sifli.com/projects/xiaozhi/' --FlushType flush